### ISSUE TITLE
Default config does not work

### ISSUE THREAD

**Issue by endegraaf** [rohan-s-raju/SimpleBlog#1]
The provided blog-Mysql-script contains Uppercase names for the tables. However when calling the login from the webapp the logs show below error:

Hibernate: select person0_.PERSON_ID as PERSON1_1_, person0_.password as password1_, person0_.ROLE_ID as ROLE4_1_, person0_.username as username1_ from Person person0_ where person0_.username=? limit ?
05-Apr-2016 14:16:18  WARN [JDBCExceptionReporter] - SQL Error: 1146, SQLState: 42S02
05-Apr-2016 14:16:18 ERROR [JDBCExceptionReporter] - Table 'blog.Person' doesn't exist

This is just an example, I have tried to correct these inconsistencies but came across many of them and finally gave up.

**Comment by rohan-s-raju** [comment]
I have fixed and add the tomcat7 plugin. update the readme file to help you.

cheers 
Rohan

**Comment by endegraaf** [comment]
Cheers, works fine now. 
Got one minor issue which I managed to fix myself. The user 'user' was unable to logout. To fix this:

add ROLE_USER to "public interface AuthenticationModelBS" class like below:
@Secured({"ROLE_ADMIN","ROLE_REGISTERED","ROLE_USER"})
